[sub-mul-common-rhs]
match.op = '-'
match.lhs = {op = '*'}
match.rhs = {op = '*'}
match.equal = [{l = [0, 1], r = [1, 1]}]

tests = [
    {from = '(a*x) - (b*x)', to = '(a-b) * x'},
]
[sub-mul-common-rhs.rewrite]
base = "(1-2) * 3"
replace = [
    [[0, 0], [0, 0]],
    [[1, 0], [0, 1]],
    [[0, 1], [1]],
]

[sub-mul-common-lhs]
match.op = '-'
match.lhs = {op = '*'}
match.rhs = {op = '*'}
match.equal = [{l = [0, 0], r = [1, 0]}]

tests = [
    {from = '(x*a) - (x*b)', to = '(a-b) * x'},
]
[sub-mul-common-lhs.rewrite]
base = "(1-2) * 3"
replace = [
    [[0, 1], [0, 0]],
    [[1, 1], [0, 1]],
    [[0, 0], [1]],
]

[add-mul-common-rhs]
match.op = '+'
match.lhs = {op = '*'}
match.rhs = {op = '*'}
match.equal = [{l = [0, 1], r = [1, 1]}]

tests = [
    {from = '(a*x) + (b*x)', to = '(a+b) * x'},
]
[add-mul-common-rhs.rewrite]
base = "(1+2) * 3"
replace = [
    [[0, 0], [0, 0]],
    [[1, 0], [0, 1]],
    [[0, 1], [1]],
]

[add-mul-common-lhs]
match.op = '+'
match.lhs = {op = '*'}
match.rhs = {op = '*'}
match.equal = [{l = [0, 0], r = [1, 0]}]

tests = [
    {from = '(x*a) + (x*b)', to = '(a+b) * x'},
]
[add-mul-common-lhs.rewrite]
base = "(1+2) * 3"
replace = [
    [[0, 1], [0, 0]],
    [[1, 1], [0, 1]],
    [[0, 0], [1]],
]

[mul-coefficients-lhs]
match.op = '*'
match.lhs = {op = 'const'}
match.rhs = {op = '*', lhs = {op = 'const'}}

tests = [
    {from = '2 * 3x', to = '6x'},
]
[mul-coefficients-lhs.rewrite]
base = "(1*2) * 3"
replace = [
    [[0], [0, 0]],
    [[1, 0], [0, 1]],
    [[1, 1], [1]],
]
fold = [
    [0],
]

[mul-nested-coefficients-lhs]
match.op = '*'
match.lhs = {op = '*', lhs = {op = 'const'}}
match.rhs = {op = '*', lhs = {op = 'const'}}
match.equal = [{l = [0, 1], r = [1, 1]}]

tests = [
    {from = '2x * 3x', to = '6 * (x*x)'},
]
[mul-nested-coefficients-lhs.rewrite]
base = "(1*2) * (3*4)"
replace = [
    [[0, 0], [0, 0]],
    [[1, 0], [0, 1]],
    [[0, 1], [1, 0]],
    [[1, 1], [1, 1]],
]
fold = [
    [0],
]

[mul-nested-coefficients-inner]
match.op = '*'
match.lhs = {op = '*', rhs = {op = 'const'}}
match.rhs = {op = '*', lhs = {op = 'const'}}
match.equal = [{l = [0, 0], r = [1, 1]}]

tests = [
    {from = '(x*4) * 3x', to = '12 * (x*x)'},
]
[mul-nested-coefficients-inner.rewrite]
base = "(1*2) * (3*4)"
replace = [
    [[0, 1], [0, 0]],
    [[1, 0], [0, 1]],
    [[0, 0], [1, 0]],
    [[1, 1], [1, 1]],
]
fold = [
    [0],
]